name: Update and Restart App on DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  update-and-restart:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SSH into server and pull
        run: |
          ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" ${{ vars.USER }}@${{ secrets.HOST }} "cd projects/dbn-tools-dcs && git pull origin main && pm2 restart dbn-tools-docs"
