name: Update and Restart App on DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  update-and-restart:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SSH into droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd projects/dbn-tools-docs/
            git pull origin main
            pm2 restart dbn-tools-docs
